name: Builds and Tests

on:
  push:
    branches: '*'
    paths-ignore:
    - README.md
    - LICENSE
    - CONTRIBUTING.md
    - .gitignore
    - '.github/**'
    - '!.github/workflows/rust.yml'

env:
  CARGO_TERM_COLOR: always

jobs:
  build_ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release
    - name: Run tests
      run: cargo test --release --verbose

    - name: Upload linux artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Linux (Ubuntu)
        path: target/release/riichi-trainer
